### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by anton0afanasiev0v** [vzhuhfaka/AlgoritmLAB1#28]
Сделай utils.py в нём будут все функции (чтения и записи в файл), которые часто используются в задачах.
Это нужно сделать для лабы 1 и 2.
Твоя задачи по максиму не дублировать код, а переиспользовать уже написанные функции.

! Оформи репозиторий https://github.com/anton0afanasiev0v/asd_labs/blob/main/Repository_design_rules.md

Вопросы можешь задать ниже

**Comment by vzhuhfaka** [comment]
А что именно оформить? Просто я вроде уже сделал по вашему шаблону, я не совсем понимаю

**Comment by vzhuhfaka** [comment]
Я всё исправил

**Comment by anton0afanasiev0v** [comment]
![image](https://github.com/user-attachments/assets/20d3dafd-6b6d-43f7-9949-d0cb6e3cf84c)
![image](https://github.com/user-attachments/assets/12b28986-4944-479a-b230-ae02c3b2469b)
Одинаковый код видишь? 
Подобная структура должна быть в каждом файле
if man должен быть в файлах задач
![image](https://github.com/user-attachments/assets/3e1bdc56-f564-4bd7-b940-9d975b948099)


Пример для тестов

```
def should_success_add_test():
  ##  given
  Pid = calculator_server:connect(),

 ##  when
  {ok, Result} = calculator_server:calculate(Pid, {add, [1, 2, 3.06, -1]}),

  ## then
  ?assertEqual(5.0600000000000005, Result).
```

Если что, то непонятно задавай вопросы

**Comment by vzhuhfaka** [comment]
А что в этой части должно находиться?
![image](https://github.com/user-attachments/assets/997b86f6-7ac5-466f-9340-c65c4a064b9e)
Просто если протестить, то тесты уже ведь написаны. Или просто вывести "now __name__ is {__name__}" ?

**Comment by anton0afanasiev0v** [comment]
Print не нужен.   Функция taskN() N -> номер задания.
![image](https://github.com/user-attachments/assets/5a08c3cc-f5e2-4877-b0d4-b0115fee2835)

**Comment by anton0afanasiev0v** [comment]
![image](https://github.com/user-attachments/assets/4f7d9eed-be39-4690-97c8-14f73864a06a)

Хотелось бы название  task5.  Если сильно хочешь то можно  task5_majority. py

**Comment by vzhuhfaka** [comment]
Сделал

**Comment by anton0afanasiev0v** [comment]
Увидел не дочёты, сил их описывать нет, давай в течение дня созвонимся, расскажу что я увидел) 

@vzhuhfaka

**Comment by vzhuhfaka** [comment]
да, можно, только во сколько? я готов где-то с 16:30

**Comment by anton0afanasiev0v** [comment]
ок, напиши в тг ближе к 16:30

**Comment by vzhuhfaka** [comment]
Я сделал изменения к первой задаче из 2 лабораторной, но пока что просто скринами скину, чтобы на гит не заливать, возможно, неверное оформление
![image](https://github.com/user-attachments/assets/626a073f-7fa7-4062-b51e-fa8d25ea05dd)
![image](https://github.com/user-attachments/assets/2bca0777-eb81-4791-a52f-270b84c10678)
![image](https://github.com/user-attachments/assets/57ae13e3-85a9-4bfb-a12e-ad5bcb854ea4)
![image](https://github.com/user-attachments/assets/2fc73682-9030-4c8e-962d-a400ac870685)
Также я добавил README.md в каждый уровень, но в гит залью только после того как с кодом разберусь
![image](https://github.com/user-attachments/assets/eeb47ee8-454f-4ff6-8f1a-511457f79ca7)

**Comment by anton0afanasiev0v** [comment]
Привет, давай в течении дня созвонимся, покажу как делать МР

**Comment by vzhuhfaka** [comment]
Ок, но я свободен буду только после 20:00

**Comment by anton0afanasiev0v** [comment]
ок давай к 9 напишешь в тг
